// Every item name the planner's game data (recipes.json `items`) has held, for checking saved
// progress that names an item (factoryGroups.local, #874) without loading recipes.json, which
// the browser edition fetches only when it calculates. Re-exported by ../state.ts.
//
// Only ever add names: a name the game data drops stays here, so progress saved while it
// existed keeps loading (validateState refuses a state naming an unknown item).
// tests/local-items.test.ts checks that every item in recipes.json is listed, and that every
// name of the pinned snapshot tests/fixtures/item-names-2026-10-03.json still is.
export const ITEM_NAMES: readonly string[] = [
  'AI Expansion Server',
  'AI Limiter',
  'Adaptive Control Unit',
  'Alclad Aluminum Sheet',
  'Alien DNA Capsule',
  'Alien Power Matrix',
  'Alien Protein',
  'Alumina Solution',
  'Aluminum Casing',
  'Aluminum Ingot',
  'Aluminum Scrap',
  'Assembly Director System',
  'Automated Wiring',
  'Bacon Agaric',
  'Ballistic Warp Drive',
  'Battery',
  'Bauxite',
  'Beryl Nut',
  'Biochemical Sculptor',
  'Biomass',
  'Black Powder',
  'Blade Runners',
  'Blue Power Slug',
  'Cable',
  'Caterium Ingot',
  'Caterium Ore',
  'Chainsaw',
  'Circuit Board',
  'Cluster Nobelisk',
  'Coal',
  'Compacted Coal',
  'Computer',
  'Concrete',
  'Cooling System',
  'Copper Ingot',
  'Copper Ore',
  'Copper Powder',
  'Copper Sheet',
  'Crude Oil',
  'Crystal Oscillator',
  'Dark Matter Crystal',
  'Dark Matter Residue',
  'Diamonds',
  'Dissolved Silica',
  'Electromagnetic Control Rod',
  'Empty Canister',
  'Empty Fluid Tank',
  'Encased Industrial Beam',
  'Encased Plutonium Cell',
  'Encased Uranium Cell',
  'Excited Photonic Matter',
  'Explosive Rebar',
  'FICSIT Coupon',
  'Fabric',
  'Factory Cart™',
  'Ficsite Ingot',
  'Ficsite Trigon',
  'Ficsonium',
  'Ficsonium Fuel Rod',
  'Fuel',
  'Fused Modular Frame',
  'Gas Filter',
  'Gas Mask',
  'Gas Nobelisk',
  'Golden Factory Cart™',
  'Hatcher Remains',
  'Hazmat Suit',
  'Heat Sink',
  'Heavy Modular Frame',
  'Heavy Oil Residue',
  'High-Speed Connector',
  'Hog Remains',
  'Homing Rifle Ammo',
  'Hoverpack',
  'Iodine-Infused Filter',
  'Ionized Fuel',
  'Iron Ingot',
  'Iron Ore',
  'Iron Plate',
  'Iron Rebar',
  'Iron Rod',
  'Jetpack',
  'Leaves',
  'Limestone',
  'Liquid Biofuel',
  'Magnetic Field Generator',
  'Medicinal Inhaler',
  'Mercer Sphere',
  'Modular Engine',
  'Modular Frame',
  'Motor',
  'Mycelia',
  'Neural-Quantum Processor',
  'Nitric Acid',
  'Nitrogen Gas',
  'Nobelisk',
  'Nobelisk Detonator',
  'Non-Fissile Uranium',
  'Nuclear Pasta',
  'Nuke Nobelisk',
  'Object Scanner',
  'Packaged Alumina Solution',
  'Packaged Fuel',
  'Packaged Heavy Oil Residue',
  'Packaged Ionized Fuel',
  'Packaged Liquid Biofuel',
  'Packaged Nitric Acid',
  'Packaged Nitrogen Gas',
  'Packaged Oil',
  'Packaged Rocket Fuel',
  'Packaged Sulfuric Acid',
  'Packaged Turbofuel',
  'Packaged Water',
  'Paleberry',
  'Parachute',
  'Petroleum Coke',
  'Plastic',
  'Plutonium Fuel Rod',
  'Plutonium Pellet',
  'Plutonium Waste',
  'Polymer Resin',
  'Portable Miner',
  'Power',
  'Power Shard',
  'Pressure Conversion Cube',
  'Pulse Nobelisk',
  'Purple Power Slug',
  'Quartz Crystal',
  'Quickwire',
  'Radio Control Unit',
  'Raw Quartz',
  'Reanimated SAM',
  'Rebar Gun',
  'Reinforced Iron Plate',
  'Rifle',
  'Rifle Ammo',
  'Rocket Fuel',
  'Rotor',
  'Rubber',
  'SAM',
  'SAM Fluctuator',
  'Screws',
  'Shatter Rebar',
  'Silica',
  'Singularity Cell',
  'Sink point',
  'Smart Plating',
  'Smokeless Powder',
  'Solid Biofuel',
  'Somersloop',
  'Spitter Remains',
  'Stator',
  'Steel Beam',
  'Steel Ingot',
  'Steel Pipe',
  'Stinger Remains',
  'Stun Rebar',
  'Sulfur',
  'Sulfuric Acid',
  'Supercomputer',
  'Superposition Oscillator',
  'Thermal Propulsion Rocket',
  'Time Crystal',
  'Turbo Motor',
  'Turbo Rifle Ammo',
  'Turbofuel',
  'Uranium',
  'Uranium Fuel Rod',
  'Uranium Waste',
  'Versatile Framework',
  'Water',
  'Wire',
  'Wood',
  'Xeno-Basher',
  'Xeno-Zapper',
  'Yellow Power Slug',
  'Zipline',
];
